# Form implementation generated from reading ui file 'checkbox.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 280, 381, 61))
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(100, 120, 571, 71))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxpython = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBoxpython.stateChanged.connect(self.check_me)
        self.checkBoxpython.setObjectName("checkBoxpython")
        self.horizontalLayout.addWidget(self.checkBoxpython)
        self.checkBox_2java = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_2java.stateChanged.connect(self.check_me)
        self.checkBox_2java.setObjectName("checkBox_2java")
        self.horizontalLayout.addWidget(self.checkBox_2java)
        self.checkBox_3C = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_3C.stateChanged.connect(self.check_me)
        self.checkBox_3C.setObjectName("checkBox_3C")
        self.horizontalLayout.addWidget(self.checkBox_3C)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def check_me(self):
        text = " "
        if self.checkBoxpython.isChecked():
            text = self.checkBoxpython.text()
        if self.checkBox_2java.isChecked():
            text = self.checkBox_2java.text()
        if self.checkBox_3C.isChecked():
            text = self.checkBox_3C.text()
        self.label.setText('You choosed: ' + text)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBoxpython.setText(_translate("MainWindow", "Python"))
        self.checkBox_2java.setText(_translate("MainWindow", "Java"))
        self.checkBox_3C.setText(_translate("MainWindow", "C++"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
