# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 535)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.num1.setGeometry(QtCore.QRect(170, 120, 113, 22))
        self.num1.setObjectName("num1")
        self.num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.num2.setGeometry(QtCore.QRect(170, 210, 113, 22))
        self.num2.setObjectName("num2")
        self.result = QtWidgets.QLineEdit(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(170, 280, 150, 22))
        self.result.setText("")
        self.result.setReadOnly(True)
        self.result.setObjectName("result")
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.clicked.connect(self.math_it)
        self.equal.setGeometry(QtCore.QRect(180, 240, 93, 28))
        self.equal.setObjectName("equal")
        self.labelofnum1 = QtWidgets.QLabel(self.centralwidget)
        self.labelofnum1.setGeometry(QtCore.QRect(180, 100, 71, 16))
        self.labelofnum1.setObjectName("labelofnum1")
        self.labelofnum2 = QtWidgets.QLabel(self.centralwidget)
        self.labelofnum2.setGeometry(QtCore.QRect(180, 190, 61, 16))
        self.labelofnum2.setObjectName("labelofnum2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 160, 403, 22))
        self.widget.setMouseTracking(True)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sum = QtWidgets.QRadioButton(self.widget)
        self.sum.setObjectName("sum")
        self.horizontalLayout.addWidget(self.sum)
        self.sub = QtWidgets.QRadioButton(self.widget)
        self.sub.setObjectName("sub")
        self.horizontalLayout.addWidget(self.sub)
        self.mult = QtWidgets.QRadioButton(self.widget)
        self.mult.setObjectName("mult")
        self.horizontalLayout.addWidget(self.mult)
        self.div = QtWidgets.QRadioButton(self.widget)
        self.div.setMouseTracking(True)
        self.div.setObjectName("div")
        self.horizontalLayout.addWidget(self.div)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def math_it(self):
        num1 = float(self.num1.text())
        num2 = float(self.num2.text())
        result = None
        if self.sum.isChecked():
            result = num1 + num2
        elif self.sub.isChecked():
            result = num1 - num2
        elif self.mult.isChecked():
            result = num1 * num2
        elif self.div.isChecked():
            if num2 != 0:
                result = num1 / num2
            else:
                result = "Error"
        self.result.setText(str(result))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple calculator"))
        self.equal.setText(_translate("MainWindow", "="))
        self.labelofnum1.setText(_translate("MainWindow", "number 1:"))
        self.labelofnum2.setText(_translate("MainWindow", "number 2:"))
        self.sum.setText(_translate("MainWindow", "sum"))
        self.sub.setText(_translate("MainWindow", "sub"))
        self.mult.setText(_translate("MainWindow", "mult"))
        self.div.setText(_translate("MainWindow", "div"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
